"""Mesh export helpers."""

from __future__ import annotations

from pathlib import Path

import numpy as np


def save_dem_as_obj(path: str | Path, dem: np.ndarray) -> str:
    """Save DEM as a Wavefront OBJ mesh."""
    out_path = Path(path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    height, width = dem.shape
    with out_path.open("w", encoding="utf-8") as f:
        f.write("# 3D mesh generated by LunarDEM\n")
        for i in range(height):
            for j in range(width):
                f.write(f"v {j} {height - 1 - i} {float(dem[i, j])}\n")
        for i in range(height - 1):
            for j in range(width - 1):
                v1 = i * width + j + 1
                v2 = v1 + 1
                v3 = (i + 1) * width + j + 2
                v4 = v3 - 1
                f.write(f"f {v1} {v2} {v3} {v4}\n")
    return str(out_path)


def save_dem_as_ply(path: str | Path, dem: np.ndarray) -> str:
    """Save DEM as ASCII PLY mesh."""
    out_path = Path(path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    height, width = dem.shape
    num_vertices = height * width
    num_faces = (height - 1) * (width - 1)

    with out_path.open("w", encoding="utf-8") as f:
        f.write("ply\n")
        f.write("format ascii 1.0\n")
        f.write(f"element vertex {num_vertices}\n")
        f.write("property float x\n")
        f.write("property float y\n")
        f.write("property float z\n")
        f.write(f"element face {num_faces}\n")
        f.write("property list uchar int vertex_indices\n")
        f.write("end_header\n")
        for i in range(height):
            for j in range(width):
                f.write(f"{j} {height - 1 - i} {float(dem[i, j])}\n")
        for i in range(height - 1):
            for j in range(width - 1):
                v1 = i * width + j
                v2 = v1 + 1
                v3 = (i + 1) * width + j + 1
                v4 = (i + 1) * width + j
                f.write(f"4 {v1} {v2} {v3} {v4}\n")
    return str(out_path)
